###
# @no-log
POST http://localhost:8080/api/workspaces/1/todoitems
Content-Type: application/json

{
  "name": "req name",
  "description": "req descr",
  "isDone": false,
  "startDateTime": "2024-06-21T16:23:49.59",
  "duration": "PT2H",
  "priority": "LOW",
  "isPostponed": false
}

###
# @no-log
GET http://localhost:8080/api/workspaces/1/todoitems

###
# @no-log
GET http://localhost:8080/api/todoitems/11

###
# @no-log
PUT http://localhost:8080/api/todoitems/11
Content-Type: application/json

{
  "name": "new name",
  "description": "new description",
  "isDone": true,
  "startDateTime": "2024-06-21T16:23:49.59",
  "duration": "PT2H",
  "priority": "HIGH",
  "isPostponed": true
}

###
# @no-log
DELETE http://localhost:8080/api/todoitems/10
