###
# @no-log
POST http://localhost:8080/api/workspaces
Content-Type: application/json

{
  "name": "payload name",
  "description": "payload descr"
}

###
# @no-log
GET http://localhost:8080/api/workspaces

###
# @no-log
GET http://localhost:8080/api/workspaces/1

###
# @no-log
PUT http://localhost:8080/api/workspaces/5
Content-Type: application/json

{
  "name": "new name",
  "description": "new description"
}

###
# @no-log
DELETE http://localhost:8080/api/workspaces/4
