-- drop table if exists to_do_item;
-- drop table if exists workspace;
-- drop table if exists customer;

create table customer
(
    id            bigint generated by default as identity not null primary key,
    username      varchar(255) unique,
    email         varchar(255) unique,
    password      varchar(255),
    role          varchar(15),
    created_at    timestamp with time zone,
    is_non_locked boolean
);

create table workspace
(
    id          bigint generated by default as identity not null primary key,
    customer_id bigint                                  not null,
    name        varchar(255),
    description varchar(511),
    created_at  timestamp with time zone,
    constraint fk_customer foreign key (customer_id) references customer (id)
);

create table to_do_item
(
    id              bigint generated by default as identity not null primary key,
    workspace_id    bigint                                  not null,
    name            varchar(255),
    description     varchar(511),
    is_done         boolean,
    start_date_time timestamp with time zone,
    duration        interval hour,
    priority        varchar(10),
    is_postponed    boolean,
    created_at      timestamp with time zone,
    constraint check_priority check (priority in ('USUAL', 'LOW', 'MIDDLE', 'HIGH')),
    constraint fk_workspace foreign key (workspace_id) references workspace (id)
);

