-- drop table if exists to_do_item;

create table to_do_item(
    id bigint generated by default as identity not null primary key,
    workspace_id bigint,
    name varchar(255),
    description varchar(511),
    is_done boolean,
    start_date_time timestamp with time zone,
    duration interval hour,
    priority varchar(10),
    is_postponed boolean,
    created_at timestamp with time zone,
    constraint priority_check check (priority in ('USUAL', 'LOW', 'MIDDLE', 'HIGH'))
);

